const descripciones_cliente = {
  cli_id: "Identificador único global del cliente.",
  cli_codigointerno: "Código de cliente interno.",
  cli_entidad: "Entidad legal o razón social asociada al registro del cliente.",
  cli_nombre_completo: "Nombre y apellidos o denominación social completa del cliente.",
  cli_apellidos_crm: "Apellidos del cliente registrados en Salesforce.",
  cli_apellidos_erp: "Apellidos del cliente registrados en Microsoft SQL Server.",
  cli_numero_documento_de_identidad: "Número de identificación fiscal (NIF/NIE/CIF) normalizado (sin guiones ni espacios).",
  cli_tipo_de_documento_de_identidad: "Tipo de documento aportado (NIF, NIE, Pasaporte, CIF).",
  cli_activo: "Indicador booleano (True/False). Define si el cliente tiene contrato o relación vigente.",
  cli_estado: "Estado actual del ciclo de vida del cliente.",
  cli_fechaalta_crm: "Fecha en la que el cliente se registró por primera vez en el CRM.",
  cli_fechaalta_erp: "Fecha en la que el cliente se registró por primera vez en el ERP.",
  cli_fechabaja_erp: "Fecha efectiva de cese de la relación comercial con el cliente en el ERP.",
  cli_comercial_asignado: "Nombre o ID del agente comercial responsable de la cuenta.",
  cli_billing_country_code: "Código ISO de dos caracteres del país de facturación (Ej: ES, EC).",
  cli_billing_state: "Provincia, estado o región de la dirección de facturación.",
  cli_email: "Dirección de correo electrónico principal (enmascaramiento PII).",
  cli_telefono_de_contacto1: "Teléfono principal de contacto, incluyendo prefijo internacional si aplica.",
  cli_ambito_de_trabajo: "Sector o área de actividad económica a la que pertenece el cliente.",
  cli_compania: "Empresa del grupo a la que pertenece o factura el cliente.",
  cli_fecha_nacimiento: "Fecha de nacimiento del cliente (Persona física). Útil para segmentación por edad.",
  cli_sexo: "Género del cliente (Hombre, Mujer, No binario, Empresa).",
  cli_observaciones_crm: "Comentarios adicionales o notas de texto libre procedentes del CRM.",
  cli_observaciones_erp: "Comentarios adicionales o notas de texto libre procedentes del ERP.",
  cli_titular_cuenta_bancaria: "Nombre del titular de la cuenta de domiciliación bancaria.",
  cli_cuenta_bancaria: "Número de cuenta (IBAN) para cobros y pagos (Dato PII).",
  cli_cuenta_bancaria_masked: "Número de cuenta (IBAN) para cobros y pagos (Dato PII). Dato enmascarado",
};

module.exports = { descripciones_cliente };